apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-system-passphrase-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    SYSTEM_PASSPHRASE: AgA7wqNj2LI02lFzY2tUOSBuf+OSSrC+u5y7fx5IKL40rGQpv7aO6xMuAzqfIoDZmh1nyGiGaGqSGMVCdiOe8TyrASSG1ntDHY2dfdI+bygAuVxGh5bsE5Fm/RWC6xFM7hOYSwODc+KVpmrYHp/fUFT2YEI+6i60ABJlNju6Q0IDYvxtk07l/ywrx0kafjK+MxXoU7/ZohcvqMeKz4Qr0tOnqFarXrjEsjEwHoahJ3UEF2SqT1lyjsnxvNTBo4kAgJDkwjDT6ZWw1IB1gf0J1mr6raIxYkfre2/kpgCe8hYByjOpTlyRrirfio0Xuiy+9BKjVyb9XDV0ZFutA/LA5FEguJPtRcnAAtPNQHT6tdSBReRIDR7W1gP6OPEOwbz9Y1HY2YM3uMqdUa2DiWpiHTFyzpVCLqUvoZ2X5vpRFf2YHnlSm3DmV2siPqNzWJgZPOwlQ3tkMzVtX/QUt2aqWPLkksyIuoYWpordagzvzjaXQHtx04StjPKNhdGWZI3GTFeNZEvdVHywYEWTLaw9DqnkUpBhC9gYaL0CQp8KNnBYgirLR73wJH0ETpVTYmmTNNALwj8jY2chkH6T1Zl8a01xsx3akmfhqOhS32WBhGol9Cv+8M3+a/kpxOnRR7quaZaUKTdNSieV9sV4BheMPAzo/HY5vtmL2BhM4qKxSxpNDTHULYEiQiZ7FkKDOO98tsijy0dH77Y+ag==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-system-passphrase-secret
      namespace: b2bi-prod
    type: Opaque

