apiVersion: batch/v1
kind: Job
metadata:
  namespace: tools
  annotations:
    argocd.argoproj.io/sync-wave: "285"
    # we need to fix the syn wave to be less than sterling-deployment
  name: "drop-b2bi"
  labels:
    app: "drop-fw"
spec:
  template:
    spec:
      serviceAccountName: b2bi
      containers:
      - name: "drop-fw-db"
        securityContext:
          runAsUser: 1010
        image: quay.io/rdecoster/delete_db2_db:1.0.1
        imagePullPolicy: Always
        command: ["bash"]
        args:
          - "-c"
          - "./deleteDB.sh"
        env:
          - name: DB_NAME
            value: "FW"
          - name: DB_HOST
            value: "ibm-sfg-db2"
          - name: DB_PORT
            value: "50000"
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: b2b-db-secret
                key: DB_USER
                optional: false
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: b2b-db-secret
                key: DB_PASSWORD
                optional: false
      restartPolicy: Never
  backoffLimit: 4